( DEFINE ( DOMAIN TABLEMOVER )
( :REQUIREMENTS :CONDITIONAL-EFFECTS :TYPING :MULTI-AGENT )
( :TYPES
	AGENT - LOCATABLE
	LOCATABLE - OBJECT
	BLOCK - LOCATABLE
	TABLE - LOCATABLE
	ROOM - OBJECT
	SIDE - OBJECT
)
( :PREDICATES
	( ON-TABLE ?BLOCK0 - BLOCK ?TABLE1 - TABLE )
	( ON-FLOOR ?BLOCK0 - BLOCK )
	( DOWN ?SIDE0 - SIDE )
	( CLEAR ?SIDE0 - SIDE )
	( AT-SIDE ?AGENT0 - AGENT ?SIDE1 - SIDE )
	( LIFTING ?AGENT0 - AGENT ?SIDE1 - SIDE )
	( HAS-SIDE ?TABLE0 - TABLE ?SIDE1 - SIDE )
	( INROOM ?LOCATABLE0 - LOCATABLE ?ROOM1 - ROOM )
	( AVAILABLE ?AGENT0 - AGENT )
	( HANDEMPTY ?AGENT0 - AGENT )
	( HOLDING ?AGENT0 - AGENT ?BLOCK1 - BLOCK )
	( CONNECTED ?ROOM0 - ROOM ?ROOM1 - ROOM )
)
( :CONCURRENT
	( PICKUP-FLOOR ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( PICKUP-TABLE ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM ?TABLE3 - TABLE )
	( PUTDOWN-TABLE ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM ?TABLE3 - TABLE )
	( TO-TABLE ?AGENT0 - AGENT ?ROOM1 - ROOM ?SIDE2 - SIDE ?TABLE3 - TABLE )
	( MOVE-TABLE ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM ?SIDE3 - SIDE ?TABLE4 - TABLE )
	( LIFT-SIDE ?AGENT0 - AGENT ?SIDE1 - SIDE ?TABLE2 - TABLE )
	( LOWER-SIDE ?AGENT0 - AGENT ?SIDE1 - SIDE ?TABLE2 - TABLE )
)
( :ACTION PICKUP-FLOOR
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( ON-FLOOR ?BLOCK1 )
		( INROOM ?AGENT0 ?ROOM2 )
		( INROOM ?BLOCK1 ?ROOM2 )
		( AVAILABLE ?AGENT0 )
		( HANDEMPTY ?AGENT0 )
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( PICKUP-FLOOR ?AGENT3 ?BLOCK1 ?ROOM2 ) )
		)
	)
  :EFFECT
	( AND
		( NOT ( ON-FLOOR ?BLOCK1 ) )
		( NOT ( HANDEMPTY ?AGENT0 ) )
		( HOLDING ?AGENT0 ?BLOCK1 )
	)
)
( :ACTION PUTDOWN-FLOOR
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK )
  :PRECONDITION
	( AND
		( AVAILABLE ?AGENT0 )
		( HOLDING ?AGENT0 ?BLOCK1 )
	)
  :EFFECT
	( AND
		( ON-FLOOR ?BLOCK1 )
		( HANDEMPTY ?AGENT0 )
		( NOT ( HOLDING ?AGENT0 ?BLOCK1 ) )
	)
)
( :ACTION PICKUP-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM ?TABLE3 - TABLE )
  :PRECONDITION
	( AND
		( ON-TABLE ?BLOCK1 ?TABLE3 )
		( INROOM ?AGENT0 ?ROOM2 )
		( INROOM ?TABLE3 ?ROOM2 )
		( AVAILABLE ?AGENT0 )
		( HANDEMPTY ?AGENT0 )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( PICKUP-TABLE ?AGENT4 ?BLOCK1 ?ROOM2 ?TABLE3 ) )
		)
	)
  :EFFECT
	( AND
		( NOT ( ON-TABLE ?BLOCK1 ?TABLE3 ) )
		( NOT ( HANDEMPTY ?AGENT0 ) )
		( HOLDING ?AGENT0 ?BLOCK1 )
	)
)
( :ACTION PUTDOWN-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM ?TABLE3 - TABLE )
  :PRECONDITION
	( AND
		( INROOM ?AGENT0 ?ROOM2 )
		( INROOM ?TABLE3 ?ROOM2 )
		( AVAILABLE ?AGENT0 )
		( HOLDING ?AGENT0 ?BLOCK1 )
	)
  :EFFECT
	( AND
		( ON-TABLE ?BLOCK1 ?TABLE3 )
		( HANDEMPTY ?AGENT0 )
		( NOT ( HOLDING ?AGENT0 ?BLOCK1 ) )
	)
)
( :ACTION TO-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?SIDE2 - SIDE ?TABLE3 - TABLE )
  :PRECONDITION
	( AND
		( CLEAR ?SIDE2 )
		( HAS-SIDE ?TABLE3 ?SIDE2 )
		( INROOM ?AGENT0 ?ROOM1 )
		( INROOM ?TABLE3 ?ROOM1 )
		( AVAILABLE ?AGENT0 )
	)
  :EFFECT
	( AND
		( NOT ( CLEAR ?SIDE2 ) )
		( AT-SIDE ?AGENT0 ?SIDE2 )
		( NOT ( AVAILABLE ?AGENT0 ) )
	)
)
( :ACTION LEAVE-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE1 - SIDE )
  :PRECONDITION
	( AND
		( AT-SIDE ?AGENT0 ?SIDE1 )
		( NOT ( LIFTING ?AGENT0 ?SIDE1 ) )
	)
  :EFFECT
	( AND
		( CLEAR ?SIDE1 )
		( NOT ( AT-SIDE ?AGENT0 ?SIDE1 ) )
		( AVAILABLE ?AGENT0 )
	)
)
( :ACTION MOVE-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM ?SIDE3 - SIDE ?TABLE4 - TABLE )
  :PRECONDITION
	( AND
		( LIFTING ?AGENT0 ?SIDE3 )
		( HAS-SIDE ?TABLE4 ?SIDE3 )
		( INROOM ?AGENT0 ?ROOM1 )
		( CONNECTED ?ROOM1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?AGENT0 ?ROOM1 ) )
		( NOT ( INROOM ?TABLE4 ?ROOM1 ) )
		( INROOM ?AGENT0 ?ROOM2 )
		( INROOM ?TABLE4 ?ROOM2 )
		( FORALL
			( ?BLOCK5 - BLOCK )
			( WHEN
				( ON-TABLE ?BLOCK5 ?TABLE4 )
				( AND
					( NOT ( INROOM ?BLOCK5 ?ROOM1 ) )
					( INROOM ?BLOCK5 ?ROOM2 )
				)
			)
		)
	)
)
( :ACTION LIFT-SIDE
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE1 - SIDE ?TABLE2 - TABLE )
  :PRECONDITION
	( AND
		( DOWN ?SIDE1 )
		( AT-SIDE ?AGENT0 ?SIDE1 )
		( HAS-SIDE ?TABLE2 ?SIDE1 )
		( HANDEMPTY ?AGENT0 )
	)
  :EFFECT
	( AND
		( NOT ( DOWN ?SIDE1 ) )
		( LIFTING ?AGENT0 ?SIDE1 )
		( NOT ( HANDEMPTY ?AGENT0 ) )
	)
)
( :ACTION LOWER-SIDE
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE1 - SIDE ?TABLE2 - TABLE )
  :PRECONDITION
	( AND
		( LIFTING ?AGENT0 ?SIDE1 )
		( HAS-SIDE ?TABLE2 ?SIDE1 )
	)
  :EFFECT
	( AND
		( DOWN ?SIDE1 )
		( NOT ( LIFTING ?AGENT0 ?SIDE1 ) )
		( HANDEMPTY ?AGENT0 )
	)
)
)
