( DEFINE ( PROBLEM TABLE4_2_1_1 )
( :DOMAIN TABLEMOVER )
( :OBJECTS
	A0 A1 - AGENT
	B0 B1 - BLOCK
	LEFT0 RIGHT0 - SIDE0
	R0 R1 R2 R3 - ROOM
)
( :INIT
	( ON-FLOOR B0 )
	( ON-FLOOR B1 )
	( INROOM B0 R1 )
	( INROOM B1 R2 )
	( INROOM A0 R2 )
	( INROOM A1 R2 )
	( AVAILABLE A0 )
	( AVAILABLE A1 )
	( HANDEMPTY A0 )
	( HANDEMPTY A1 )
	( CONNECTED R0 R3 )
	( CONNECTED R3 R0 )
	( CONNECTED R3 R1 )
	( CONNECTED R1 R3 )
	( CONNECTED R0 R2 )
	( CONNECTED R2 R0 )
	( DOWN LEFT0 )
	( DOWN RIGHT0 )
	( CLEAR LEFT0 )
	( CLEAR RIGHT0 )
	( INROOM TABLE0 R2 )
)
( :GOAL
	( AND
		( DOWN LEFT0 )
		( DOWN RIGHT0 )
		( ON-FLOOR B0 )
		( ON-FLOOR B1 )
		( INROOM B0 R1 )
		( INROOM B1 R1 )
	)
)
)
