( DEFINE ( DOMAIN TABLEMOVER )
( :REQUIREMENTS :CONDITIONAL-EFFECTS :TYPING :MULTI-AGENT )
( :TYPES
	AGENT - LOCATABLE
	LOCATABLE - OBJECT
	BLOCK - LOCATABLE
	TABLE - LOCATABLE
	SIDE0 - SIDE
	SIDE - OBJECT
	ROOM - OBJECT
)
( :CONSTANTS
	TABLE0 - TABLE
)
( :PREDICATES
	( ON-TABLE ?BLOCK0 - BLOCK ?TABLE1 - TABLE )
	( ON-FLOOR ?BLOCK0 - BLOCK )
	( DOWN ?SIDE0 - SIDE )
	( UP ?SIDE0 - SIDE )
	( CLEAR ?SIDE0 - SIDE )
	( AT-SIDE ?AGENT0 - AGENT ?SIDE1 - SIDE )
	( LIFTING ?AGENT0 - AGENT ?SIDE1 - SIDE )
	( INROOM ?LOCATABLE0 - LOCATABLE ?ROOM1 - ROOM )
	( AVAILABLE ?AGENT0 - AGENT )
	( HANDEMPTY ?AGENT0 - AGENT )
	( HOLDING ?AGENT0 - AGENT ?BLOCK1 - BLOCK )
	( CONNECTED ?ROOM0 - ROOM ?ROOM1 - ROOM )
)
( :ACTION PICKUP-FLOOR
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( ON-FLOOR ?BLOCK1 )
		( INROOM ?AGENT ?ROOM2 )
		( INROOM ?BLOCK1 ?ROOM2 )
		( AVAILABLE ?AGENT )
		( HANDEMPTY ?AGENT )
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( PICKUP-FLOOR ?AGENT3 ?BLOCK1 ?ROOM2 ) )
		)
	)
  :EFFECT
	( AND
		( NOT ( ON-FLOOR ?BLOCK1 ) )
		( NOT ( INROOM ?BLOCK1 ?ROOM2 ) )
		( NOT ( HANDEMPTY ?AGENT ) )
		( HOLDING ?AGENT ?BLOCK1 )
	)
)
( :ACTION PUTDOWN-FLOOR
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( AVAILABLE ?AGENT )
		( INROOM ?AGENT ?ROOM2 )
		( HOLDING ?AGENT ?BLOCK1 )
	)
  :EFFECT
	( AND
		( ON-FLOOR ?BLOCK1 )
		( INROOM ?BLOCK1 ?ROOM2 )
		( HANDEMPTY ?AGENT )
		( NOT ( HOLDING ?AGENT ?BLOCK1 ) )
	)
)
( :ACTION PICKUP-TABLE-0
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( ON-TABLE ?BLOCK1 TABLE0 )
		( INROOM ?AGENT ?ROOM2 )
		( INROOM TABLE0 ?ROOM2 )
		( AVAILABLE ?AGENT )
		( HANDEMPTY ?AGENT )
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( PICKUP-TABLE-0 ?AGENT3 ?BLOCK1 ?ROOM2 ) )
		)
	)
  :EFFECT
	( AND
		( NOT ( ON-TABLE ?BLOCK1 TABLE0 ) )
		( NOT ( HANDEMPTY ?AGENT ) )
		( HOLDING ?AGENT ?BLOCK1 )
	)
)
( :ACTION PUTDOWN-TABLE-0
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( INROOM TABLE0 ?ROOM2 )
		( AVAILABLE ?AGENT )
		( HOLDING ?AGENT ?BLOCK1 )
		( FORALL
			( ?SIDE03 - SIDE0 )
			( DOWN ?SIDE03 )
		)
		( FORALL
			( ?AGENT3 - AGENT ?SIDE04 - SIDE0 )
			( NOT ( LIFT-SIDE-0 ?AGENT3 ?SIDE04 ) )
		)
	)
  :EFFECT
	( AND
		( ON-TABLE ?BLOCK1 TABLE0 )
		( HANDEMPTY ?AGENT )
		( NOT ( HOLDING ?AGENT ?BLOCK1 ) )
	)
)
( :ACTION TO-TABLE-0
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?ROOM1 - ROOM ?SIDE02 - SIDE0 )
  :PRECONDITION
	( AND
		( CLEAR ?SIDE02 )
		( INROOM ?AGENT ?ROOM1 )
		( INROOM TABLE0 ?ROOM1 )
		( AVAILABLE ?AGENT )
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( TO-TABLE-0 ?AGENT3 ?ROOM1 ?SIDE02 ) )
		)
	)
  :EFFECT
	( AND
		( NOT ( CLEAR ?SIDE02 ) )
		( AT-SIDE ?AGENT ?SIDE02 )
		( NOT ( AVAILABLE ?AGENT ) )
	)
)
( :ACTION LEAVE-TABLE-0
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( AT-SIDE ?AGENT ?SIDE01 )
		( NOT ( LIFTING ?AGENT ?SIDE01 ) )
	)
  :EFFECT
	( AND
		( CLEAR ?SIDE01 )
		( NOT ( AT-SIDE ?AGENT ?SIDE01 ) )
		( AVAILABLE ?AGENT )
	)
)
( :ACTION MOVE-TABLE-0
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?ROOM1 - ROOM ?ROOM2 - ROOM ?SIDE03 - SIDE0 )
  :PRECONDITION
	( AND
		( LIFTING ?AGENT ?SIDE03 )
		( INROOM ?AGENT ?ROOM1 )
		( CONNECTED ?ROOM1 ?ROOM2 )
		( EXISTS
			( ?AGENT4 - AGENT ?SIDE05 - SIDE0 )
			( AND
				( NOT ( = ?SIDE03 ?SIDE05 ) )
				( MOVE-TABLE-0 ?AGENT4 ?ROOM1 ?ROOM2 ?SIDE05 )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?AGENT ?ROOM1 ) )
		( NOT ( INROOM TABLE0 ?ROOM1 ) )
		( INROOM ?AGENT ?ROOM2 )
		( INROOM TABLE0 ?ROOM2 )
	)
)
( :ACTION LIFT-SIDE-0
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( DOWN ?SIDE01 )
		( AT-SIDE ?AGENT ?SIDE01 )
		( HANDEMPTY ?AGENT )
		( FORALL
			( ?AGENT2 - AGENT ?SIDE03 - SIDE0 )
			( NOT ( LOWER-SIDE-0 ?AGENT2 ?SIDE03 ) )
		)
	)
  :EFFECT
	( AND
		( NOT ( DOWN ?SIDE01 ) )
		( UP ?SIDE01 )
		( LIFTING ?AGENT ?SIDE01 )
		( NOT ( HANDEMPTY ?AGENT ) )
		( FORALL
			( ?BLOCK2 - BLOCK ?ROOM3 - ROOM ?SIDE04 - SIDE0 )
			( WHEN
				( AND
					( INROOM TABLE0 ?ROOM3 )
					( ON-TABLE ?BLOCK2 TABLE0 )
					( DOWN ?SIDE04 )
					( FORALL
						( ?AGENT5 - AGENT )
						( NOT ( LIFT-SIDE-0 ?AGENT5 ?SIDE04 ) )
					)
				)
				( AND
					( ON-FLOOR ?BLOCK2 )
					( INROOM ?BLOCK2 ?ROOM3 )
					( NOT ( ON-TABLE ?BLOCK2 TABLE0 ) )
				)
			)
		)
	)
)
( :ACTION LOWER-SIDE-0
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( LIFTING ?AGENT ?SIDE01 )
		( FORALL
			( ?AGENT2 - AGENT ?SIDE03 - SIDE0 )
			( NOT ( LIFT-SIDE-0 ?AGENT2 ?SIDE03 ) )
		)
	)
  :EFFECT
	( AND
		( DOWN ?SIDE01 )
		( NOT ( UP ?SIDE01 ) )
		( NOT ( LIFTING ?AGENT ?SIDE01 ) )
		( HANDEMPTY ?AGENT )
		( FORALL
			( ?BLOCK2 - BLOCK ?ROOM3 - ROOM ?SIDE04 - SIDE0 )
			( WHEN
				( AND
					( INROOM TABLE0 ?ROOM3 )
					( ON-TABLE ?BLOCK2 TABLE0 )
					( UP ?SIDE04 )
					( FORALL
						( ?AGENT5 - AGENT )
						( NOT ( LOWER-SIDE-0 ?AGENT5 ?SIDE04 ) )
					)
				)
				( AND
					( ON-FLOOR ?BLOCK2 )
					( INROOM ?BLOCK2 ?ROOM3 )
					( NOT ( ON-TABLE ?BLOCK2 TABLE0 ) )
				)
			)
		)
	)
)
)
