( DEFINE ( DOMAIN LOGISTICS )
( :REQUIREMENTS :EQUALITY :NEGATIVE-PRECONDITIONS :CONDITIONAL-EFFECTS :TYPING :UNIVERSAL-PRECONDITIONS )
( :TYPES
	LOCATION - OBJECT
	VEHICLE - AGENT
	PACKAGE - OBJECT
	CITY - OBJECT
	AIRPORT - LOCATION
	TRUCK - VEHICLE
	AIRPLANE - VEHICLE
	AGENT - OBJECT
)
( :CONSTANTS
)
( :PREDICATES
	( FREE-BLOCK )
	( SELECTING )
	( APPLYING )
	( RESETTING )
	( FREE-AGENT ?AGENT0 - AGENT )
	( BUSY-AGENT ?AGENT0 - AGENT )
	( DONE-AGENT ?AGENT0 - AGENT )
	( AT ?OBJECT0 - OBJECT ?LOCATION1 - LOCATION )
	( IN ?PACKAGE0 - PACKAGE ?VEHICLE1 - VEHICLE )
	( IN-CITY ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?CITY2 - CITY )
	( ACTIVE-LOAD-AIRPLANE ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
	( REQ-NEG-LOAD-AIRPLANE ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
	( ACTIVE-UNLOAD-AIRPLANE ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
	( REQ-NEG-UNLOAD-AIRPLANE ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
	( ACTIVE-FLY-AIRPLANE ?AIRPLANE0 - AIRPLANE ?AIRPORT1 - AIRPORT ?AIRPORT2 - AIRPORT )
	( REQ-NEG-FLY-AIRPLANE ?AIRPLANE0 - AIRPLANE ?AIRPORT1 - AIRPORT ?AIRPORT2 - AIRPORT )
	( ACTIVE-LOAD-TRUCK ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
	( REQ-NEG-LOAD-TRUCK ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
	( ACTIVE-UNLOAD-TRUCK ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
	( REQ-NEG-UNLOAD-TRUCK ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
	( ACTIVE-DRIVE-TRUCK ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?CITY3 - CITY )
	( REQ-NEG-DRIVE-TRUCK ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?CITY3 - CITY )
)
( :ACTION START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( FREE-BLOCK )
	)
  :EFFECT
	( AND
		( NOT ( FREE-BLOCK ) )
		( SELECTING )
	)
)
( :ACTION APPLY
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( SELECTING )
	)
  :EFFECT
	( AND
		( NOT ( SELECTING ) )
		( APPLYING )
	)
)
( :ACTION RESET
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( APPLYING )
	)
  :EFFECT
	( AND
		( NOT ( APPLYING ) )
		( RESETTING )
	)
)
( :ACTION FINISH
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( RESETTING )
		( FORALL
			( ?AGENT0 - AGENT )
			( FREE-AGENT ?AGENT0 )
		)
	)
  :EFFECT
	( AND
		( NOT ( RESETTING ) )
		( FREE-BLOCK )
	)
)
( :ACTION SELECT-LOAD-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AIRPLANE0 )
		( NOT ( REQ-NEG-LOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 ) )
		( AT ?PACKAGE1 ?AIRPORT2 )
		( AT ?AIRPLANE0 ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AIRPLANE0 ) )
		( BUSY-AGENT ?AIRPLANE0 )
		( ACTIVE-LOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 )
	)
)
( :ACTION DO-LOAD-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AIRPLANE0 )
		( ACTIVE-LOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AIRPLANE0 ) )
		( DONE-AGENT ?AIRPLANE0 )
		( NOT ( AT ?PACKAGE1 ?AIRPORT2 ) )
		( IN ?PACKAGE1 ?AIRPLANE0 )
	)
)
( :ACTION END-LOAD-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AIRPLANE0 )
		( ACTIVE-LOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AIRPLANE0 ) )
		( FREE-AGENT ?AIRPLANE0 )
		( NOT ( ACTIVE-LOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 ) )
	)
)
( :ACTION SELECT-UNLOAD-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AIRPLANE0 )
		( NOT ( REQ-NEG-UNLOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 ) )
		( IN ?PACKAGE1 ?AIRPLANE0 )
		( AT ?AIRPLANE0 ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AIRPLANE0 ) )
		( BUSY-AGENT ?AIRPLANE0 )
		( ACTIVE-UNLOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 )
	)
)
( :ACTION DO-UNLOAD-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AIRPLANE0 )
		( ACTIVE-UNLOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AIRPLANE0 ) )
		( DONE-AGENT ?AIRPLANE0 )
		( NOT ( IN ?PACKAGE1 ?AIRPLANE0 ) )
		( AT ?PACKAGE1 ?AIRPORT2 )
	)
)
( :ACTION END-UNLOAD-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AIRPLANE0 )
		( ACTIVE-UNLOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AIRPLANE0 ) )
		( FREE-AGENT ?AIRPLANE0 )
		( NOT ( ACTIVE-UNLOAD-AIRPLANE ?AIRPLANE0 ?PACKAGE1 ?AIRPORT2 ) )
	)
)
( :ACTION SELECT-FLY-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?AIRPORT1 - AIRPORT ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AIRPLANE0 )
		( NOT ( REQ-NEG-FLY-AIRPLANE ?AIRPLANE0 ?AIRPORT1 ?AIRPORT2 ) )
		( AT ?AIRPLANE0 ?AIRPORT1 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AIRPLANE0 ) )
		( BUSY-AGENT ?AIRPLANE0 )
		( ACTIVE-FLY-AIRPLANE ?AIRPLANE0 ?AIRPORT1 ?AIRPORT2 )
	)
)
( :ACTION DO-FLY-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?AIRPORT1 - AIRPORT ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AIRPLANE0 )
		( ACTIVE-FLY-AIRPLANE ?AIRPLANE0 ?AIRPORT1 ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AIRPLANE0 ) )
		( DONE-AGENT ?AIRPLANE0 )
		( NOT ( AT ?AIRPLANE0 ?AIRPORT1 ) )
		( AT ?AIRPLANE0 ?AIRPORT2 )
	)
)
( :ACTION END-FLY-AIRPLANE
  :PARAMETERS ( ?AIRPLANE0 - AIRPLANE ?AIRPORT1 - AIRPORT ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AIRPLANE0 )
		( ACTIVE-FLY-AIRPLANE ?AIRPLANE0 ?AIRPORT1 ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AIRPLANE0 ) )
		( FREE-AGENT ?AIRPLANE0 )
		( NOT ( ACTIVE-FLY-AIRPLANE ?AIRPLANE0 ?AIRPORT1 ?AIRPORT2 ) )
	)
)
( :ACTION SELECT-LOAD-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?TRUCK0 )
		( NOT ( REQ-NEG-LOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 ) )
		( AT ?TRUCK0 ?LOCATION2 )
		( AT ?PACKAGE1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?TRUCK0 ) )
		( BUSY-AGENT ?TRUCK0 )
		( ACTIVE-LOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 )
	)
)
( :ACTION DO-LOAD-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?TRUCK0 )
		( ACTIVE-LOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?TRUCK0 ) )
		( DONE-AGENT ?TRUCK0 )
		( NOT ( AT ?PACKAGE1 ?LOCATION2 ) )
		( IN ?PACKAGE1 ?TRUCK0 )
	)
)
( :ACTION END-LOAD-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?TRUCK0 )
		( ACTIVE-LOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?TRUCK0 ) )
		( FREE-AGENT ?TRUCK0 )
		( NOT ( ACTIVE-LOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 ) )
	)
)
( :ACTION SELECT-UNLOAD-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?TRUCK0 )
		( NOT ( REQ-NEG-UNLOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 ) )
		( AT ?TRUCK0 ?LOCATION2 )
		( IN ?PACKAGE1 ?TRUCK0 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?TRUCK0 ) )
		( BUSY-AGENT ?TRUCK0 )
		( ACTIVE-UNLOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 )
	)
)
( :ACTION DO-UNLOAD-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?TRUCK0 )
		( ACTIVE-UNLOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?TRUCK0 ) )
		( DONE-AGENT ?TRUCK0 )
		( NOT ( IN ?PACKAGE1 ?TRUCK0 ) )
		( AT ?PACKAGE1 ?LOCATION2 )
	)
)
( :ACTION END-UNLOAD-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?TRUCK0 )
		( ACTIVE-UNLOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?TRUCK0 ) )
		( FREE-AGENT ?TRUCK0 )
		( NOT ( ACTIVE-UNLOAD-TRUCK ?TRUCK0 ?PACKAGE1 ?LOCATION2 ) )
	)
)
( :ACTION SELECT-DRIVE-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?CITY3 - CITY )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?TRUCK0 )
		( NOT ( REQ-NEG-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?CITY3 ) )
		( AT ?TRUCK0 ?LOCATION1 )
		( IN-CITY ?TRUCK0 ?LOCATION1 ?CITY3 )
		( IN-CITY ?TRUCK0 ?LOCATION2 ?CITY3 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?TRUCK0 ) )
		( BUSY-AGENT ?TRUCK0 )
		( ACTIVE-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?CITY3 )
	)
)
( :ACTION DO-DRIVE-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?CITY3 - CITY )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?TRUCK0 )
		( ACTIVE-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?CITY3 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?TRUCK0 ) )
		( DONE-AGENT ?TRUCK0 )
		( NOT ( AT ?TRUCK0 ?LOCATION1 ) )
		( AT ?TRUCK0 ?LOCATION2 )
	)
)
( :ACTION END-DRIVE-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?CITY3 - CITY )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?TRUCK0 )
		( ACTIVE-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?CITY3 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?TRUCK0 ) )
		( FREE-AGENT ?TRUCK0 )
		( NOT ( ACTIVE-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?CITY3 ) )
	)
)
)
