( DEFINE ( DOMAIN LOGISTICS )
( :REQUIREMENTS :STRIPS :TYPING :MULTI-AGENT :UNFACTORED-PRIVACY )
( :TYPES
	AIRPORT - LOCATION
	LOCATION - OBJECT
	TRUCK - VEHICLE
	VEHICLE - OBJECT
	AIRPLANE - VEHICLE
	PACKAGE - OBJECT
	CITY - OBJECT
)
( :PREDICATES
	( AT ?OBJECT0 - OBJECT ?LOCATION1 - LOCATION )
	( IN ?PACKAGE0 - PACKAGE ?VEHICLE1 - VEHICLE )
	( IN-CITY ?LOCATION0 - LOCATION ?CITY1 - CITY )
)
( :ACTION LOAD-AIRPLANE
  :AGENT ?AIRPLANE - AIRPLANE
  :PARAMETERS ( ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( AT ?PACKAGE1 ?AIRPORT2 )
		( AT ?AIRPLANE ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( AT ?PACKAGE1 ?AIRPORT2 ) )
		( IN ?PACKAGE1 ?AIRPLANE )
	)
)
( :ACTION UNLOAD-AIRPLANE
  :AGENT ?AIRPLANE - AIRPLANE
  :PARAMETERS ( ?PACKAGE1 - PACKAGE ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AND
		( IN ?PACKAGE1 ?AIRPLANE )
		( AT ?AIRPLANE ?AIRPORT2 )
	)
  :EFFECT
	( AND
		( NOT ( IN ?PACKAGE1 ?AIRPLANE ) )
		( AT ?PACKAGE1 ?AIRPORT2 )
	)
)
( :ACTION FLY-AIRPLANE
  :AGENT ?AIRPLANE - AIRPLANE
  :PARAMETERS ( ?AIRPORT1 - AIRPORT ?AIRPORT2 - AIRPORT )
  :PRECONDITION
	( AT ?AIRPLANE ?AIRPORT1 )
  :EFFECT
	( AND
		( NOT ( AT ?AIRPLANE ?AIRPORT1 ) )
		( AT ?AIRPLANE ?AIRPORT2 )
	)
)
( :ACTION LOAD-TRUCK
  :AGENT ?TRUCK - TRUCK
  :PARAMETERS ( ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?TRUCK ?LOCATION2 )
		( AT ?PACKAGE1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( AT ?PACKAGE1 ?LOCATION2 ) )
		( IN ?PACKAGE1 ?TRUCK )
	)
)
( :ACTION UNLOAD-TRUCK
  :AGENT ?TRUCK - TRUCK
  :PARAMETERS ( ?PACKAGE1 - PACKAGE ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?TRUCK ?LOCATION2 )
		( IN ?PACKAGE1 ?TRUCK )
	)
  :EFFECT
	( AND
		( NOT ( IN ?PACKAGE1 ?TRUCK ) )
		( AT ?PACKAGE1 ?LOCATION2 )
	)
)
( :ACTION DRIVE-TRUCK
  :AGENT ?TRUCK - TRUCK
  :PARAMETERS ( ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?CITY3 - CITY )
  :PRECONDITION
	( AND
		( AT ?TRUCK ?LOCATION1 )
		( IN-CITY ?LOCATION1 ?CITY3 )
		( IN-CITY ?LOCATION2 ?CITY3 )
	)
  :EFFECT
	( AND
		( NOT ( AT ?TRUCK ?LOCATION1 ) )
		( AT ?TRUCK ?LOCATION2 )
	)
)
)
