(define

 (problem wireless-03)
 (:domain wireless)
 (:objects
  base - base
  node1 node2 node3 node4 node5 - sensor
  msg1-1 msg2-1 msg3-1 msg4-1 msg5-1 - message  ;; ...just like tokens in a Petri-net.
 )

 (:init
  (not-sending node1 node1 msg5-1)
  (not-sending node4 node1 msg5-1)
  (not-sending node5 node1 msg5-1)
  (not-sending node2 node1 msg5-1)
  (not-sending node3 node1 msg5-1)
  (not-sending node1 node4 msg5-1)
  (not-sending node4 node4 msg5-1)
  (not-sending node5 node4 msg5-1)
  (not-sending node2 node4 msg5-1)
  (not-sending node3 node4 msg5-1)
  (not-sending node1 base msg5-1)
  (not-sending node4 base msg5-1)
  (not-sending node5 base msg5-1)
  (not-sending node2 base msg5-1)
  (not-sending node3 base msg5-1)
  (not-sending node1 node5 msg5-1)
  (not-sending node4 node5 msg5-1)
  (not-sending node5 node5 msg5-1)
  (not-sending node2 node5 msg5-1)
  (not-sending node3 node5 msg5-1)
  (not-sending node1 node2 msg5-1)
  (not-sending node4 node2 msg5-1)
  (not-sending node5 node2 msg5-1)
  (not-sending node2 node2 msg5-1)
  (not-sending node3 node2 msg5-1)
  (not-sending node1 node3 msg5-1)
  (not-sending node4 node3 msg5-1)
  (not-sending node5 node3 msg5-1)
  (not-sending node2 node3 msg5-1)
  (not-sending node3 node3 msg5-1)
  (not-sending node1 node1 msg3-1)
  (not-sending node4 node1 msg3-1)
  (not-sending node5 node1 msg3-1)
  (not-sending node2 node1 msg3-1)
  (not-sending node3 node1 msg3-1)
  (not-sending node1 node4 msg3-1)
  (not-sending node4 node4 msg3-1)
  (not-sending node5 node4 msg3-1)
  (not-sending node2 node4 msg3-1)
  (not-sending node3 node4 msg3-1)
  (not-sending node1 base msg3-1)
  (not-sending node4 base msg3-1)
  (not-sending node5 base msg3-1)
  (not-sending node2 base msg3-1)
  (not-sending node3 base msg3-1)
  (not-sending node1 node5 msg3-1)
  (not-sending node4 node5 msg3-1)
  (not-sending node5 node5 msg3-1)
  (not-sending node2 node5 msg3-1)
  (not-sending node3 node5 msg3-1)
  (not-sending node1 node2 msg3-1)
  (not-sending node4 node2 msg3-1)
  (not-sending node5 node2 msg3-1)
  (not-sending node2 node2 msg3-1)
  (not-sending node3 node2 msg3-1)
  (not-sending node1 node3 msg3-1)
  (not-sending node4 node3 msg3-1)
  (not-sending node5 node3 msg3-1)
  (not-sending node2 node3 msg3-1)
  (not-sending node3 node3 msg3-1)
  (not-sending node1 node1 msg1-1)
  (not-sending node4 node1 msg1-1)
  (not-sending node5 node1 msg1-1)
  (not-sending node2 node1 msg1-1)
  (not-sending node3 node1 msg1-1)
  (not-sending node1 node4 msg1-1)
  (not-sending node4 node4 msg1-1)
  (not-sending node5 node4 msg1-1)
  (not-sending node2 node4 msg1-1)
  (not-sending node3 node4 msg1-1)
  (not-sending node1 base msg1-1)
  (not-sending node4 base msg1-1)
  (not-sending node5 base msg1-1)
  (not-sending node2 base msg1-1)
  (not-sending node3 base msg1-1)
  (not-sending node1 node5 msg1-1)
  (not-sending node4 node5 msg1-1)
  (not-sending node5 node5 msg1-1)
  (not-sending node2 node5 msg1-1)
  (not-sending node3 node5 msg1-1)
  (not-sending node1 node2 msg1-1)
  (not-sending node4 node2 msg1-1)
  (not-sending node5 node2 msg1-1)
  (not-sending node2 node2 msg1-1)
  (not-sending node3 node2 msg1-1)
  (not-sending node1 node3 msg1-1)
  (not-sending node4 node3 msg1-1)
  (not-sending node5 node3 msg1-1)
  (not-sending node2 node3 msg1-1)
  (not-sending node3 node3 msg1-1)
  (not-sending node1 node1 msg4-1)
  (not-sending node4 node1 msg4-1)
  (not-sending node5 node1 msg4-1)
  (not-sending node2 node1 msg4-1)
  (not-sending node3 node1 msg4-1)
  (not-sending node1 node4 msg4-1)
  (not-sending node4 node4 msg4-1)
  (not-sending node5 node4 msg4-1)
  (not-sending node2 node4 msg4-1)
  (not-sending node3 node4 msg4-1)
  (not-sending node1 base msg4-1)
  (not-sending node4 base msg4-1)
  (not-sending node5 base msg4-1)
  (not-sending node2 base msg4-1)
  (not-sending node3 base msg4-1)
  (not-sending node1 node5 msg4-1)
  (not-sending node4 node5 msg4-1)
  (not-sending node5 node5 msg4-1)
  (not-sending node2 node5 msg4-1)
  (not-sending node3 node5 msg4-1)
  (not-sending node1 node2 msg4-1)
  (not-sending node4 node2 msg4-1)
  (not-sending node5 node2 msg4-1)
  (not-sending node2 node2 msg4-1)
  (not-sending node3 node2 msg4-1)
  (not-sending node1 node3 msg4-1)
  (not-sending node4 node3 msg4-1)
  (not-sending node5 node3 msg4-1)
  (not-sending node2 node3 msg4-1)
  (not-sending node3 node3 msg4-1)
  (not-sending node1 node1 msg2-1)
  (not-sending node4 node1 msg2-1)
  (not-sending node5 node1 msg2-1)
  (not-sending node2 node1 msg2-1)
  (not-sending node3 node1 msg2-1)
  (not-sending node1 node4 msg2-1)
  (not-sending node4 node4 msg2-1)
  (not-sending node5 node4 msg2-1)
  (not-sending node2 node4 msg2-1)
  (not-sending node3 node4 msg2-1)
  (not-sending node1 base msg2-1)
  (not-sending node4 base msg2-1)
  (not-sending node5 base msg2-1)
  (not-sending node2 base msg2-1)
  (not-sending node3 base msg2-1)
  (not-sending node1 node5 msg2-1)
  (not-sending node4 node5 msg2-1)
  (not-sending node5 node5 msg2-1)
  (not-sending node2 node5 msg2-1)
  (not-sending node3 node5 msg2-1)
  (not-sending node1 node2 msg2-1)
  (not-sending node4 node2 msg2-1)
  (not-sending node5 node2 msg2-1)
  (not-sending node2 node2 msg2-1)
  (not-sending node3 node2 msg2-1)
  (not-sending node1 node3 msg2-1)
  (not-sending node4 node3 msg2-1)
  (not-sending node5 node3 msg2-1)
  (not-sending node2 node3 msg2-1)
  (not-sending node3 node3 msg2-1)
  (not-message-data msg5-1 node1)
  (not-message-data msg3-1 node1)
  (not-message-data msg1-1 node1)
  (not-message-data msg4-1 node1)
  (not-message-data msg2-1 node1)
  (not-message-data msg5-1 node4)
  (not-message-data msg3-1 node4)
  (not-message-data msg1-1 node4)
  (not-message-data msg4-1 node4)
  (not-message-data msg2-1 node4)
  (not-message-data msg5-1 node5)
  (not-message-data msg3-1 node5)
  (not-message-data msg1-1 node5)
  (not-message-data msg4-1 node5)
  (not-message-data msg2-1 node5)
  (not-message-data msg5-1 node2)
  (not-message-data msg3-1 node2)
  (not-message-data msg1-1 node2)
  (not-message-data msg4-1 node2)
  (not-message-data msg2-1 node2)
  (not-message-data msg5-1 node3)
  (not-message-data msg3-1 node3)
  (not-message-data msg1-1 node3)
  (not-message-data msg4-1 node3)
  (not-message-data msg2-1 node3)
  (not-message-at msg5-1 node1)
  (not-message-at msg3-1 node1)
  (not-message-at msg4-1 node1)
  (not-message-at msg2-1 node1)
  (not-message-at msg5-1 node4)
  (not-message-at msg3-1 node4)
  (not-message-at msg1-1 node4)
  (not-message-at msg4-1 node4)
  (not-message-at msg2-1 node4)
  (not-message-at msg5-1 base)
  (not-message-at msg3-1 base)
  (not-message-at msg1-1 base)
  (not-message-at msg4-1 base)
  (not-message-at msg2-1 base)
  (not-message-at msg5-1 node5)
  (not-message-at msg3-1 node5)
  (not-message-at msg1-1 node5)
  (not-message-at msg4-1 node5)
  (not-message-at msg2-1 node5)
  (not-message-at msg5-1 node2)
  (not-message-at msg3-1 node2)
  (not-message-at msg1-1 node2)
  (not-message-at msg4-1 node2)
  (not-message-at msg2-1 node2)
  (not-message-at msg5-1 node3)
  (not-message-at msg3-1 node3)
  (not-message-at msg1-1 node3)
  (not-message-at msg4-1 node3)
  (not-message-at msg2-1 node3)

  ;; CONFIGURATION DATA
  (higher High Low)
  (higher High Normal)
  (higher High Zero)
  (higher Normal Low)
  (higher Normal Zero)
  (higher Low Zero)

  (next High Normal)
  (next  Normal Low)
  (next  Low Zero)

  ;; NODE1 INFO
  (energy node1 Normal)
  (is-message-at msg1-1 node1)

  ;; NODE2 INFO
  (energy node2 Normal)

  ;; NODE3 INFO
  (energy node3 Normal)

  ;; NODE4 INFO
  (energy node4 Normal)

  ;; NODE5 INFO
  (energy node5 High)

  ;; NODE RELATIONS
  (neighbor node1 node2)
  (neighbor node2 node1)
  (neighbor node2 node3)
  (neighbor node3 node2)
  (neighbor node3 node4)
  (neighbor node4 node3)
  (neighbor node3 node5)
  (neighbor node5 node3)
  (neighbor node4 node5)
  (neighbor node5 node4)
  (neighbor node5 base)
  (neighbor base node5)

 )

 (:goal
  (and (has-data base node1)
    (has-data base node2)
    (has-data base node3)
    (has-data base node4)
    (has-data base node5)
  )
 )

)
