( DEFINE ( DOMAIN WORKSHOP )
( :REQUIREMENTS :CONDITIONAL-EFFECTS :TYPING :MULTI-AGENT :CONCURRENCY-NETWORK )
( :TYPES
	AGENT - LOCATABLE
	LOCATABLE - OBJECT
	FORKLIFT - LOCATABLE
	KEY - LOCATABLE
	PALLET - LOCATABLE
	SWITCH - LOCATABLE
	DOOR - OBJECT
	ROOM - OBJECT
)
( :PREDICATES
	( INROOM ?LOCATABLE0 - LOCATABLE ?ROOM1 - ROOM )
	( EMPTY ?FORKLIFT0 - FORKLIFT )
	( HOLDING ?AGENT0 - AGENT ?KEY1 - KEY )
	( DRIVING ?AGENT0 - AGENT ?FORKLIFT1 - FORKLIFT )
	( LOCKED ?DOOR0 - DOOR )
	( UNLOCKED ?DOOR0 - DOOR )
	( FITS ?KEY0 - KEY ?DOOR1 - DOOR )
	( CONNECTED ?SWITCH0 - SWITCH ?DOOR1 - DOOR )
	( EXAMINED ?PALLET0 - PALLET )
	( ADJACENT ?ROOM0 - ROOM ?ROOM1 - ROOM ?DOOR2 - DOOR )
)
( :ACTION PICKUP
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?KEY1 - KEY ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( INROOM ?KEY1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?KEY1 ?ROOM2 ) )
		( HOLDING ?AGENT ?KEY1 )
	)
)
( :ACTION UNLOCK
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?KEY1 - KEY ?ROOM2 - ROOM ?ROOM3 - ROOM ?DOOR4 - DOOR )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( HOLDING ?AGENT ?KEY1 )
		( LOCKED ?DOOR4 )
		( FITS ?KEY1 ?DOOR4 )
		( ADJACENT ?ROOM2 ?ROOM3 ?DOOR4 )
	)
  :EFFECT
	( AND
		( NOT ( LOCKED ?DOOR4 ) )
		( UNLOCKED ?DOOR4 )
	)
)
( :ACTION PRESS-SWITCH
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?SWITCH1 - SWITCH ?ROOM2 - ROOM ?DOOR3 - DOOR )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( INROOM ?SWITCH1 ?ROOM2 )
		( CONNECTED ?SWITCH1 ?DOOR3 )
	)
  :EFFECT
	()
)
( :ACTION ENTER-FORKLIFT
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?FORKLIFT1 - FORKLIFT ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( INROOM ?FORKLIFT1 ?ROOM2 )
		( EMPTY ?FORKLIFT1 )
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?AGENT ?ROOM2 ) )
		( DRIVING ?AGENT ?FORKLIFT1 )
		( NOT ( EMPTY ?FORKLIFT1 ) )
	)
)
( :ACTION EXIT-FORKLIFT
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?FORKLIFT1 - FORKLIFT ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( DRIVING ?AGENT ?FORKLIFT1 )
		( INROOM ?FORKLIFT1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( NOT ( DRIVING ?AGENT ?FORKLIFT1 ) )
		( EMPTY ?FORKLIFT1 )
	)
)
( :ACTION MOVE-AGENT
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?ROOM1 - ROOM ?ROOM2 - ROOM ?DOOR3 - DOOR )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM1 )
		( UNLOCKED ?DOOR3 )
		( ADJACENT ?ROOM1 ?ROOM2 ?DOOR3 )
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?AGENT ?ROOM1 ) )
		( INROOM ?AGENT ?ROOM2 )
	)
)
( :ACTION DRIVE-FORKLIFT
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?FORKLIFT1 - FORKLIFT ?ROOM2 - ROOM ?ROOM3 - ROOM ?DOOR4 - DOOR )
  :PRECONDITION
	( AND
		( DRIVING ?AGENT ?FORKLIFT1 )
		( INROOM ?FORKLIFT1 ?ROOM2 )
		( UNLOCKED ?DOOR4 )
		( ADJACENT ?ROOM2 ?ROOM3 ?DOOR4 )
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?FORKLIFT1 ?ROOM2 ) )
		( INROOM ?FORKLIFT1 ?ROOM3 )
	)
)
( :ACTION EXAMINE-PALLET
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?ROOM1 - ROOM ?PALLET2 - PALLET )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM1 )
		( INROOM ?PALLET2 ?ROOM1 )
	)
  :EFFECT
	( AND
		( EXAMINED ?PALLET2 )
	)
)
( :ACTION LIFT-PALLET
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?FORKLIFT1 - FORKLIFT ?ROOM2 - ROOM ?PALLET3 - PALLET )
  :PRECONDITION
	( AND
		( DRIVING ?AGENT ?FORKLIFT1 )
		( INROOM ?FORKLIFT1 ?ROOM2 )
		( INROOM ?PALLET3 ?ROOM2 )
	)
  :EFFECT
	()
)
( :CONCURRENCY-CONSTRAINT V1
  :PARAMETERS ( ?KEY0 - KEY )
  :BOUNDS ( 1 1 )
  :ACTIONS ( ( PICKUP 1 ) )
)
( :CONCURRENCY-CONSTRAINT V2
  :PARAMETERS ( ?DOOR0 - DOOR )
  :BOUNDS ( 1 1 )
  :ACTIONS ( ( UNLOCK 4 ) )
)
( :CONCURRENCY-CONSTRAINT V3
  :PARAMETERS ( ?DOOR0 - DOOR )
  :BOUNDS ( 1 1 )
  :ACTIONS ( ( PRESS-SWITCH 3 ) )
)
( :CONCURRENCY-CONSTRAINT V4
  :PARAMETERS ( ?FORKLIFT0 - FORKLIFT )
  :BOUNDS ( 1 1 )
  :ACTIONS ( ( ENTER-FORKLIFT 1 ) ( EXIT-FORKLIFT 1 ) )
)
( :CONCURRENCY-CONSTRAINT V5
  :PARAMETERS ( ?AGENT0 - AGENT )
  :BOUNDS ( 1 1 )
  :ACTIONS ( ( MOVE-AGENT 0 ) ( DRIVE-FORKLIFT 0 ) )
)
( :CONCURRENCY-CONSTRAINT V6
  :PARAMETERS ( ?PALLET0 - PALLET )
  :BOUNDS ( 1 1 )
  :ACTIONS ( ( EXAMINE-PALLET 2 ) )
)
( :CONCURRENCY-CONSTRAINT V7
  :PARAMETERS ( ?PALLET0 - PALLET )
  :BOUNDS ( 1 1 )
  :ACTIONS ( ( LIFT-PALLET 3 ) )
)
( :POSITIVE-DEPENDENCE V3 V2 )
( :POSITIVE-DEPENDENCE V7 V6 )
)
