( DEFINE ( DOMAIN WORKSHOP )
( :REQUIREMENTS :CONDITIONAL-EFFECTS :TYPING :MULTI-AGENT )
( :TYPES
	AGENT - LOCATABLE
	LOCATABLE - OBJECT
	FORKLIFT - LOCATABLE
	KEY - LOCATABLE
	PALLET - LOCATABLE
	SWITCH - LOCATABLE
	DOOR - OBJECT
	ROOM - OBJECT
)
( :PREDICATES
	( INROOM ?LOCATABLE0 - LOCATABLE ?ROOM1 - ROOM )
	( EMPTY ?FORKLIFT0 - FORKLIFT )
	( HOLDING ?AGENT0 - AGENT ?KEY1 - KEY )
	( DRIVING ?AGENT0 - AGENT ?FORKLIFT1 - FORKLIFT )
	( LOCKED ?DOOR0 - DOOR )
	( UNLOCKED ?DOOR0 - DOOR )
	( FITS ?KEY0 - KEY ?DOOR1 - DOOR )
	( CONNECTED ?SWITCH0 - SWITCH ?DOOR1 - DOOR )
	( EXAMINED ?PALLET0 - PALLET )
	( ADJACENT ?ROOM0 - ROOM ?ROOM1 - ROOM ?DOOR2 - DOOR )
)
( :ACTION PICKUP
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?KEY1 - KEY ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( INROOM ?KEY1 ?ROOM2 )
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( PICKUP ?AGENT3 ?KEY1 ?ROOM2 ) )
		)
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?KEY1 ?ROOM2 ) )
		( HOLDING ?AGENT ?KEY1 )
	)
)
( :ACTION UNLOCK
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?KEY1 - KEY ?ROOM2 - ROOM ?ROOM3 - ROOM ?DOOR4 - DOOR )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( HOLDING ?AGENT ?KEY1 )
		( LOCKED ?DOOR4 )
		( FITS ?KEY1 ?DOOR4 )
		( ADJACENT ?ROOM2 ?ROOM3 ?DOOR4 )
		( EXISTS
			( ?AGENT5 - AGENT ?ROOM6 - ROOM ?SWITCH7 - SWITCH )
			( AND
				( NOT ( = ?AGENT ?AGENT5 ) )
				( PRESS-SWITCH ?AGENT5 ?SWITCH7 ?ROOM6 ?DOOR4 )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( LOCKED ?DOOR4 ) )
		( UNLOCKED ?DOOR4 )
	)
)
( :ACTION PRESS-SWITCH
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?SWITCH1 - SWITCH ?ROOM2 - ROOM ?DOOR3 - DOOR )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( INROOM ?SWITCH1 ?ROOM2 )
		( CONNECTED ?SWITCH1 ?DOOR3 )
	)
  :EFFECT
	()
)
( :ACTION ENTER-FORKLIFT
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?FORKLIFT1 - FORKLIFT ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( INROOM ?FORKLIFT1 ?ROOM2 )
		( EMPTY ?FORKLIFT1 )
		( FORALL
			( ?AGENT3 - AGENT ?ROOM4 - ROOM )
			( NOT ( ENTER-FORKLIFT ?AGENT3 ?FORKLIFT1 ?ROOM4 ) )
		)
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?AGENT ?ROOM2 ) )
		( DRIVING ?AGENT ?FORKLIFT1 )
		( NOT ( EMPTY ?FORKLIFT1 ) )
	)
)
( :ACTION EXIT-FORKLIFT
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?FORKLIFT1 - FORKLIFT ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( DRIVING ?AGENT ?FORKLIFT1 )
		( INROOM ?FORKLIFT1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( INROOM ?AGENT ?ROOM2 )
		( NOT ( DRIVING ?AGENT ?FORKLIFT1 ) )
		( EMPTY ?FORKLIFT1 )
	)
)
( :ACTION MOVE-AGENT
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?ROOM1 - ROOM ?ROOM2 - ROOM ?DOOR3 - DOOR )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM1 )
		( UNLOCKED ?DOOR3 )
		( ADJACENT ?ROOM1 ?ROOM2 ?DOOR3 )
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?AGENT ?ROOM1 ) )
		( INROOM ?AGENT ?ROOM2 )
	)
)
( :ACTION DRIVE-FORKLIFT
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?FORKLIFT1 - FORKLIFT ?ROOM2 - ROOM ?ROOM3 - ROOM ?DOOR4 - DOOR )
  :PRECONDITION
	( AND
		( DRIVING ?AGENT ?FORKLIFT1 )
		( INROOM ?FORKLIFT1 ?ROOM2 )
		( UNLOCKED ?DOOR4 )
		( ADJACENT ?ROOM2 ?ROOM3 ?DOOR4 )
	)
  :EFFECT
	( AND
		( NOT ( INROOM ?FORKLIFT1 ?ROOM2 ) )
		( INROOM ?FORKLIFT1 ?ROOM3 )
	)
)
( :ACTION EXAMINE-PALLET
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?ROOM1 - ROOM ?PALLET2 - PALLET )
  :PRECONDITION
	( AND
		( INROOM ?AGENT ?ROOM1 )
		( INROOM ?PALLET2 ?ROOM1 )
		( EXISTS
			( ?AGENT3 - AGENT ?FORKLIFT4 - FORKLIFT )
			( AND
				( NOT ( = ?AGENT ?AGENT3 ) )
				( LIFT-PALLET ?AGENT3 ?FORKLIFT4 ?ROOM1 ?PALLET2 )
			)
		)
	)
  :EFFECT
	( AND
		( EXAMINED ?PALLET2 )
	)
)
( :ACTION LIFT-PALLET
  :AGENT ?AGENT - AGENT
  :PARAMETERS ( ?FORKLIFT1 - FORKLIFT ?ROOM2 - ROOM ?PALLET3 - PALLET )
  :PRECONDITION
	( AND
		( DRIVING ?AGENT ?FORKLIFT1 )
		( INROOM ?FORKLIFT1 ?ROOM2 )
		( INROOM ?PALLET3 ?ROOM2 )
	)
  :EFFECT
	()
)
)
